
HTTPPort : 4571
ServiceName : uploadapi
BasePath : http://localhost
HttpRequestLimit : 10

#config database dev local
DBType : mongodb
DBUser : root
DBPassword : root_password
DBHost : mongodb://localhost:27019/
DBName : data

# path for save file
RootFile : D:/tmp/file